[package]
name = "yapgeir_graphics_hal"
version = "0.1.0"
edition = "2021"

[dependencies]
yapgeir_graphics_hal_macro = { path = "./macro" }

derive_more.workspace = true
bytemuck.workspace = true
smart-default.workspace = true
enum-map.workspace = true
