[package]
name = "yapgeir_geometry"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
yapgeir_reflection = { path = "../yapgeir_reflection" }
derive_more.workspace = true
