[package]
name = "yapgeir_geometry"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
reflection = ["dep:yapgeir_reflection"]

[dependencies]
yapgeir_reflection = { path = "../yapgeir_reflection", optional = true }
derive_more.workspace = true
