[package]
name = "yapgeir_egui_painter"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
yapgeir_graphics_hal = { path = "../yapgeir_graphics_hal" }
bytemuck.workspace = true
egui.workspace = true
