[package]
name = "yapgeir_reflection"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
yapgeir_realm = { path = "../yapgeir_realm"}
derive_more.workspace = true
bevy_reflect.workspace = true
hecs.workspace = true