[package]
name = "yapgeir_input"
version = "0.1.0"
edition = "2021"

[dependencies]
yapgeir_realm = { path = "../yapgeir_realm" }
derive_more.workspace = true
bitvec.workspace = true
nalgebra.workspace = true
strum.workspace = true
indexmap.workspace = true