[package]
name = "yapgeir_collections_macro"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
convert_case.workspace = true
darling.workspace = true
quote.workspace = true
syn.workspace = true
proc-macro2.workspace = true